In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize
import numpy as np
import nltk
from nltk.corpus import stopwords
from sklearn.metrics.pairwise import cosine_similarity
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!unzip -q /content/test_data.zip

In [5]:
import os

folder_path = "/content/test_data"
file_list = os.listdir(folder_path)
doc = "document_"
nums = []
for x in file_list:
  num = x[len(doc):x.find('.')]
  nums.append(int(num))
text_list = []
for num in sorted(nums):
    file_name = f"{doc}{num}.txt"
    if file_name.endswith(".txt"):
        file_path = os.path.join(folder_path, file_name)
        with open(file_path, "r") as f:
            text = f.read()
            text_list.append(text)

print(text_list[2])

Apothem. The apothem of a regular polygon is a segment drawn the center of the polygon (that is, the center of the circle which circumscribes the polygon) to one side, such that it is perpendicular to the side. If a regular polygon has an area of A square units, a perimeter of P units, an apothem of a units, then the area is one-half the product of the perimeter and the apothem. Be careful with this formula, though: for a given apothem, there is only ONE POSSIBLE value of P.
Apothems. The apothem of a regular polygon is the distance from the center to the midpoint of one of its sides. The apothem of a square is equal to half of the length of one side. 
Apothem of a Regular Polygon. Definition: A line segment from the center of a regular polygon to the midpoint of a side. Try this Adjust the polygon below by dragging any orange dot, or alter the number of sides. Note the behavior of the apothem line shown in blue. The word apothem can refer to the line itself, or the length of that line

In [6]:
print(text_list[5].split('\n')[0])

Like many other early information technologies, EDI was inspired by developments in military logistics. The complexity of the 1948 Berlin airlift required the development of concepts and methods to exchange, sometimes over a 300 baud teletype modem, vast quantities of data and information about transported goods. In EDI terminology inbound and outbound refer to the direction of transmission of an EDI document in relation to a particular system, not the direction of merchandise, money or other things represented by the document.



Part 0:

In [7]:
def preprocess(text):
  text = text.lower()
  words = word_tokenize(text)
  stop_words = set(stopwords.words('english'))
  filtered_words = [word for word in words if word.isalnum() or word.isdigit() and word not in stop_words]
  return filtered_words

tokenizing:

In [8]:
Tokenized_list = [preprocess(text) for text in text_list]


In [9]:
print(Tokenized_list[0])

['we', 'have', 'been', 'feeding', 'our', 'back', 'yard', 'squirrels', 'for', 'the', 'fall', 'and', 'winter', 'and', 'we', 'noticed', 'that', 'a', 'few', 'of', 'them', 'have', 'missing', 'fur', 'one', 'has', 'a', 'patch', 'missing', 'down', 'his', 'back', 'and', 'under', 'both', 'arms', 'also', 'another', 'has', 'some', 'missing', 'on', 'his', 'whole', 'chest', 'they', 'are', 'all', 'eating', 'and', 'seem', 'to', 'have', 'a', 'good', 'appetite', 'critters', 'can', 'not', 'stand', 'the', 'smell', 'of', 'human', 'hair', 'so', 'sprinkling', 'a', 'barrier', 'of', 'hair', 'clippings', 'around', 'your', 'garden', 'or', 'lightly', 'working', 'it', 'into', 'the', 'soil', 'when', 'you', 'plant', 'bulbs', 'apparently', 'does', 'have', 'some', 'merit', 'the', 'whole', 'thing', 'kind', 'of', 'makes', 'me', 'laugh', 'it', 'never', 'occurred', 'to', 'me', 'that', 'we', 'are', 'the', 'ones', 'that', 'stink', 'spread', 'some', 'human', 'hair', 'around', 'your', 'vegetable', 'and', 'flower', 'gardens', 

In [10]:
Tokenized_set = [set(l) for l in Tokenized_list]


In [11]:
V = set()
for i in Tokenized_set:
    V.update(i)

In [12]:
IDF = dict()
for text in Tokenized_set:
  for word in text:
    if word in IDF.keys():
      IDF[word] += 1
    else:
      IDF[word] = 1

Part1

In [13]:
from collections import Counter
def tf_idf(ind):
  tf = Counter(Tokenized_list[ind])

  w = []
  for i in Tokenized_list[ind]:
    w.append(np.log10(1 + tf[i]) * np.log10(float(len(Tokenized_list)) /(1.0 + float(IDF[i])) ))

  #print(idf)
  return w

In [14]:
Splited_list = [text.split("\n") for text in text_list]
print(Splited_list[0][1])

Critters cannot stand the smell of human hair, so sprinkling a barrier of hair clippings around your garden, or lightly working it into the soil when you plant bulbs, apparently does have some merit. The whole thing kind of makes me laugh. It never occurred to me that we are the ones that stink.


In [15]:
def par_tf_idf(ind , npar):
  tf = Counter(preprocess(Splited_list[ind][npar]))

  w = []
  for i in preprocess(Splited_list[ind][npar]):
    if IDF[i] == 0:
      print(i)
      continue
    w.append(np.log10(1 + tf[i]) * np.log10(float(len(Tokenized_list)) / (1 + float(IDF[i])) ))


  #print(idf)
  return w

In [ ]:
print(word_tokenize(Splited_list[3][2]))
print(par_tf_idf(3 , 2))

['The', 'right', 'Naproxen', 'dosage', '.', 'Naproxen', 'dosage', 'recommendations', 'for', 'treating', 'pain', 'in', 'osteoarthritis', ',', 'vary', 'between', '500', 'mg', 'and', '1000', 'mg', 'daily', '.', 'The', 'maximum', 'Naproxen', 'dosage', 'per', 'day', 'is', '1500', 'mg', '.', 'In', 'order', 'to', 'avoid', 'any', 'stomach', 'upset', 'is', 'better', 'to', 'take', 'your', 'daily', 'dosage', 'of', 'Naproxen', 'after', 'meals', 'or', 'with', 'a', 'glass', 'of', 'milk', '.', 'The', 'best', 'dosage', 'for', 'arthritis', 'is', 'the', 'same', 'as', 'in', 'case', 'of', 'osteoarthritis', ',', 'and', 'it', 'ranges', 'between', '500', 'mg', 'to']
[0.11354335715356942, 0.937201152630621, 14.795914760555197, 10.38382333586252, 0.019811747589856078, 14.795914760555197, 10.38382333586252, 2.233595838690381, 0.08935396327463646, 1.791567329364213, 1.1962785148282364, 0.009923444652015551, 4.7915652654366205, 0.010239780875739466, 0.9490106066293962, 0.9258406468004896, 2.6547135259255557, 7.24

PART 1.1:

In [16]:
VocabIndex = {word: index for index, word in enumerate(V)}

In [17]:
Mapped_list = []
for Tl in Tokenized_list:
  ml = [VocabIndex[word] for word in Tl]
  Mapped_list.append(ml)


In [ ]:
print(Mapped_list[0])

[158823, 389299, 375123, 133848, 1703, 56644, 389695, 405760, 34436, 299892, 173109, 363255, 133848, 390384, 219106, 104532, 149266, 286453, 227187, 39458, 1703, 425395, 291458, 25263, 365238, 67651, 264604, 126624, 356568, 396578, 128048, 146467, 148202, 326072, 40097, 56675, 227187, 9951, 131310, 196270, 133848, 342391, 387421, 133848, 267888, 408310, 49338, 181147, 60105, 196270, 128048, 375123, 409218, 227089, 266686, 331324, 30954, 78031, 394437, 285722, 196270, 410316, 182267, 103079, 228484, 227187, 161986, 257133, 375542, 196270, 133848, 1703, 56644, 310397, 160869, 119307, 375349, 146647, 365238, 260520, 375123, 391407, 205803, 378871, 408310, 119307, 133848, 163556, 222614, 423629, 227187, 9951, 369623, 235652, 196270, 128048, 19233, 1703, 308713, 434982, 292727, 353638, 86747, 36642, 81309, 115334, 117302, 128048, 56644, 279640, 342391, 408310, 225460, 374508, 324639, 375123, 175864, 133848, 369623, 235652, 250585, 146473, 2581, 133848, 279640, 438010, 403419, 87063, 133848,

Par2:


In [18]:
def par_tf_idf_vectorizer(ind , npar):
  w = par_tf_idf(ind , npar)
  vec = np.zeros(len(V))
  for weight , word in zip(w , preprocess(Splited_list[ind][npar])):
    vec[VocabIndex[word]] = weight
  return vec

In [19]:
def doc_tf_idf_vectorizer(ind):
  w = tf_idf(ind)
  vec = np.zeros(len(V))
  for weight , word in zip(w , Tokenized_list[ind]):
    vec[VocabIndex[word]] = weight
  return vec

In [20]:
from difflib import get_close_matches
def find_most_similar_word(query, stored_words):
    cms = get_close_matches(query, stored_words)
    if len(cms) > 0:
        return cms[0]

        return ""

In [21]:
def Query_tfidf_vectorizer(query):
  tokenized_query = preprocess(query)
  query =[find_most_similar_word(word, V) for word in tokenized_query]

  tf = Counter(query)
  queryset = set(query)
  vec = np.zeros(len(V))

  w = []
  for i in query:
    if IDF[i] == 0:
      print(i)
      continue
    w.append(np.log10(1 +tf[i]) * np.log10(float(len(Tokenized_list)) / float(IDF[i])))

  for weight , word in zip(w , query):
    vec[VocabIndex[word]] = weight

  return vec

In [22]:
v = par_tf_idf_vectorizer(3 , 2)
x = np.argsort(v)[::-1][0:5]
print(v[x])

[1.44396508 1.28794306 1.20392618 0.9484893  0.93470029]


In [23]:
v = doc_tf_idf_vectorizer(3)
x = np.argsort(v)[::-1][0:5]
print(v[x])

[3.17117649 2.10054466 2.02686124 1.95256298 1.91013479]


In [24]:
v = Query_tfidf_vectorizer("The most expendive patents are international patents")
x = np.argsort(v)[::-1][0:5]
print(v[x])
# expendive have been trasnformed to expensive

[1.43157087 0.42426249 0.4055541  0.07477153 0.01773748]


In [ ]:
Part3:

In [25]:
def cosine_similarity(a, b):
    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    return dot_product / (norm_a * norm_b)

In [26]:
import json
with open('/content/test_data.json', 'r') as file:
    Queries = json.load(file)
query = Queries[0]['query']
print(query)

Yes


In [ ]:
for i in range(54000 , 54016):

  print(f"Query_id:{i}")
  query = Queries[i]['query']
  candidates = Queries[i]['candidate_documents_id']
  print(f"Query:{query}")
  print(f"Candidates:{candidates}")
  ans = Queries[i]['document_id']
  print(f"Query Answer: {ans}")
  parlist = Queries[i]['is_selected']
  anspar = 0
  for x , y in enumerate(parlist):
    if y == 1:
      anspar = x
  print(f"Ans is in Sentence:{anspar}")


  queryvec = Query_tfidf_vectorizer(query)

  x = np.argsort(queryvec)[::-1][0:5]

  sims = []
  for j , can in enumerate(candidates):
    docvec = doc_tf_idf_vectorizer(can)
    x = np.argsort(docvec)[::-1][0:5]

    sims.append( (cosine_similarity(queryvec , docvec) , can))
  sims = sorted(sims , reverse=True)
  print(sims[:5])

  print(f"Most similar:{sims[0][1]}")


  ind = sims[0][1]
  parsims = []
  for j in range(len(Splited_list[ind])):
    parvec = par_tf_idf_vectorizer(ind , j)
    parsims.append((cosine_similarity(queryvec , parvec) , j))
  print(parsims)
  parsims = sorted(parsims , reverse=True)
  print("Part Of Context:")
  print(Splited_list[ind][parsims[0][1]])
  print(f"Num sent find in:{parsims[0][1]}")


  print("--------------------------------------------------------\n\n")

Query_id:54000
Query:Genetically modified (GM) foods are foods derived from organisms whose genetic material (DNA) has been modified in a way that does not occur naturally.
Candidates:[5004, 36066, 9706, 8080, 34543, 45159, 49779, 11050, 41256, 10273, 30225, 19105, 1675, 40948, 46812, 12884, 1651, 41457, 1031, 49225]
Query Answer: 49225
Ans is in Sentence:5


KeyboardInterrupt: ignored

In [28]:
import random

random_numbers = random.sample(range(1, 1001), 100)
cnt = 0
for i in random_numbers:

  query = Queries[i]['query']
  candidates = Queries[i]['candidate_documents_id']
  ans = Queries[i]['document_id']
  parlist = Queries[i]['is_selected']
  anspar = 0
  for x , y in enumerate(parlist):
    if y == 1:
      anspar = x


  queryvec = Query_tfidf_vectorizer(query)

  x = np.argsort(queryvec)[::-1][0:5]

  sims = []
  for j , can in enumerate(candidates):
    docvec = doc_tf_idf_vectorizer(can)
    x = np.argsort(docvec)[::-1][0:5]

    sims.append( (cosine_similarity(queryvec , docvec) , can))
  sims = sorted(sims , reverse=True)



  ind = sims[0][1]
  if ind == ans :
    cnt += 1


print(cnt)

94


80% accuracy

Part4:

In [30]:
stl = []
for tl in Tokenized_list:
  tf = Counter(tl)
  stl.append(sorted(tf.items(), key=lambda x:x[1] , reverse = True))
stl[0]

[('the', 16),
 ('a', 11),
 ('of', 10),
 ('squirrels', 9),
 ('and', 9),
 ('hair', 9),
 ('your', 7),
 ('it', 7),
 ('have', 6),
 ('that', 6),
 ('is', 6),
 ('to', 5),
 ('can', 5),
 ('human', 5),
 ('around', 5),
 ('garden', 5),
 ('in', 5),
 ('been', 4),
 ('has', 4),
 ('some', 4),
 ('or', 4),
 ('you', 4),
 ('this', 4),
 ('will', 4),
 ('mange', 4),
 ('we', 3),
 ('for', 3),
 ('missing', 3),
 ('also', 3),
 ('are', 3),
 ('into', 3),
 ('soil', 3),
 ('me', 3),
 ('i', 3),
 ('back', 2),
 ('fall', 2),
 ('one', 2),
 ('his', 2),
 ('under', 2),
 ('both', 2),
 ('on', 2),
 ('whole', 2),
 ('so', 2),
 ('lightly', 2),
 ('when', 2),
 ('plant', 2),
 ('bulbs', 2),
 ('spread', 2),
 ('humans', 2),
 ('if', 2),
 ('up', 2),
 ('1', 2),
 ('2', 2),
 ('3', 2),
 ('high', 2),
 ('4', 2),
 ('there', 2),
 ('her', 2),
 ('from', 2),
 ('caused', 2),
 ('by', 2),
 ('disease', 2),
 ('my', 2),
 ('once', 2),
 ('via', 2),
 ('feeding', 1),
 ('our', 1),
 ('yard', 1),
 ('winter', 1),
 ('noticed', 1),
 ('few', 1),
 ('them', 1),
 ('fur', 

Part5:

In [31]:
def top5(ind):
  w = tf_idf(ind)
  top_indices = np.argsort(w)
  res = []
  res.append(top_indices[-1])
  for i in reversed(list(top_indices)):
    if Tokenized_list[ind][i] != Tokenized_list[ind][res[-1]]:
      res.append(i)
    if len(res) == 5:
      return res
  return res
for i in top5(0):
  print(Tokenized_list[0][i])

squirrels
mange
hair
garden
missing
